alter table public.profiles
  add column if not exists skin_type text not null default 'combination',
  add column if not exists skin_concerns text[] not null default '{}',
  add column if not exists skin_sensitivities text[] not null default '{}';

create table if not exists public.daily_check_ins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tags text[] not null default '{}',
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists daily_check_ins_user_created_idx
  on public.daily_check_ins (user_id, created_at desc);

grant select, insert, delete on public.daily_check_ins to authenticated;
alter table public.daily_check_ins enable row level security;

create policy "Users can read their own daily check-ins"
on public.daily_check_ins for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own daily check-ins"
on public.daily_check_ins for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own daily check-ins"
on public.daily_check_ins for delete to authenticated
using ((select auth.uid()) = user_id);
