-- roster_entries: 근무표(날짜별 근무 코드).
create table if not exists public.roster_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  work_date date not null,
  shift_type text not null check (shift_type in ('D', 'E', 'N', 'O')),
  created_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create index if not exists roster_entries_user_date_idx
  on public.roster_entries (user_id, work_date desc);

grant select, insert, update, delete on public.roster_entries to authenticated;
alter table public.roster_entries enable row level security;

create policy "Users can read their own roster entries"
on public.roster_entries for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own roster entries"
on public.roster_entries for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own roster entries"
on public.roster_entries for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own roster entries"
on public.roster_entries for delete to authenticated
using ((select auth.uid()) = user_id);

-- health_daily_metrics: 날짜별 실측(또는 데모) 수면·HRV·심박 요약.
create table if not exists public.health_daily_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  metric_date date not null,
  sleep_start timestamptz not null,
  sleep_end timestamptz not null,
  sleep_minutes int not null,
  hrv_z double precision,
  resting_heart_rate double precision,
  source text not null default 'demo_watch',
  created_at timestamptz not null default now(),
  unique (user_id, metric_date),
  check (sleep_end > sleep_start)
);

create index if not exists health_daily_metrics_user_date_idx
  on public.health_daily_metrics (user_id, metric_date desc);

grant select, insert, update, delete on public.health_daily_metrics to authenticated;
alter table public.health_daily_metrics enable row level security;

create policy "Users can read their own health metrics"
on public.health_daily_metrics for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own health metrics"
on public.health_daily_metrics for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own health metrics"
on public.health_daily_metrics for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own health metrics"
on public.health_daily_metrics for delete to authenticated
using ((select auth.uid()) = user_id);
